const Lng = {
  Home:'الرئيسية',
 MAIN: 'الرئيسي',
 User: 'المستخدم',
 brand: 'كورسي',
 register: 'تسجيل',
 login: 'الدخول',
 user: 'مستخدم',
 item: 'عنصر',
 Information: 'معلومات',
 item_price: 'سعر العنصر:',
 Discount: 'خصم:',
 tax: 'ضريبة:',
 total: 'الاجمالي:',
 Payment_gateway: 'الدفع',
 pay: 'ادفع',
 have_giftcard: 'هل لديك خصم هو بطاقة هدية؟',
 profile: 'الملف الشخصي',
 support: 'الدعم',
 comments: 'تعليقات',
 lessons: 'الكورسات',
 details: 'تفاصيل',
 leave_comment: 'أترك تعليقاً.... ',
 write_support: 'اكتب رسالة لقسم الدعم',
 support_is_disabled: 'هذا الكورس غير مدعم',
 send_support_massage: 'إرسال رسالة دعم',
 write_a_review: 'اكتب رأيك',
 write_a_review_first: 'الرجاء كتابة رأيك اولاً',
 enroll_on_the_course: 'الإنظمام بهذا الكورس',
 newest_courses: 'الكورسات الأحدث',
 view_all: 'عرض الكل',
 most_popular_courses: 'الكورسات الأكثر شيوعاً',
 most_viewed_courses: 'الكورسات الأكثر مشاهدة',
 featured_courses: 'الكورسات القادمة',
 home: 'الرئيسية',
 onboarding1: 'ادرس من اي مكان',
 onboarding1_sub: 'ويه كورسي',
 onboarding2: 'درس مادتك بسهولة',
 onboarding2_sub: 'وأحصل على دخل',
 onboarding3: 'خليك متقدم دائماً',
 onboarding3_sub: 'واستثمر وقتك ',
 search: 'بحث',
 Category: 'الصف',
 course_categories: 'كورسات الصفوف',
 News: 'الأخبار',
 More: 'المزيد',
 Latest_news: 'أخر الاخبار',
 Latest_articles: 'أخر المقالات',
 coming_soon_courses: 'قريبــــاً',
 Course_requests: 'طلب كورس',
 Follow: 'متابعة',
 Courses: 'الكورسات',
 my_courses: 'كورساتي',
 back_to_categories: 'العودة إلى الصف',
 Minutes: 'دفيقة',
 Followers: 'المتابعين',
 Bio: 'حول',
 Badges: 'الشارات',
 Articles: 'المقالات',
 Login: 'الدخول',
 Send: 'ارسال',
 please_login: 'الرجاء تسجيل الدخول إلى حسابك',
 purchase_first: 'العنصر غير مباع!',
 Email_address: 'البريد الإلكتروني',
 Password: 'كلمة السر',
 re_password: 'أعادة كلمة السر',
 access_denied: 'فشل بالدخول، تم حظر حسابك حتى  ',
 incorrect_login: 'هناك خطأ في اسم المستخدم أو كلمة المرور!',
 pass_confirm_alert: 'كلمة المرور غير متطابقة',
 password_changed: 'تم تغير كلمة المرور بنجاح',
 user_not_found: 'المتسخدم غير موجود',
 pass_change_link: 'تم إرسال رابط تغير كلمة المرور لبريدك الإلكتروني',
 new_pass_email: 'تم إرسال كلمة السر الجديدة لبريدك الإلكتروني',
 user_exists: 'المستخدم موجود ',
 thanks_reg: 'شكراً على تسجيلك بكورسي',
 active_account_alert: 'شكراً على تسجيلك ، رجاءاً راجع بريدك الالكتروني حتى تفعل حسابك ',
 login_request: 'ادخل لحسابك وارسل الطلب',
 Register: 'تسجيل',
 email_ph: 'بريدك الالكتروني',
 username_ph: 'أسم المستخدم',
 retype_ph: 'أعادة كلمة المرور',
 realname_ph: 'اسمك الحقيقي الثلاثي',
 password_ph: 'كلمة مرورك',
 enjoy_product: 'وهسه استمتع بكورسي !',
 forget_password: 'نسيت كلمة المرور',
 Already_have_an_account: 'انته مسجل اصلاً',
 Your_problem_solved: 'انحلت مشكلتك؟',
 Back_to_Login: 'ارجع للدخول',
 simply_email: 'بكل سهولة عن طريق البريد الالكتروني',
 recover: 'استرجاع كلمة مرورك',
 reset_password: 'تغير كلمة المرور',
 enter_email_reset_password: 'اكتب بريدك الالكتروني وراح نرسلك رابط تغير كلمة المرور، وتدلل',
 username: 'اسم المستخدم:',
 login_to_purchase: 'حبيبي لازم تدخل بحسابك حتى تسجل بالكورس',
 i_accept: 'موافق',
 term_rules: 'الشروط والقوانين',
 entered_username_exists: 'اسم المستخدم موجود، حاول واحد ثاني',
 entered_email_exists: 'البريد الالكتروني مسجل، حاول واحد ثاني',
 pass_confirmation_same: 'كلمة المرور غير متطابقة، حاول مره ثانية',
 active_account: 'تفعيل الحساب',
 activation: 'تفعيل',
 successfully_done: 'نجاح العملية',
 account_activation_success: 'ممتاز حسابك اتفعل انطلق ويه كورسي',
 Dashboard: 'لوحة التحكم',
 Channels: 'القنوات',
 Channel: 'القناة',
 Financial: 'مالي',
 My_courses: 'كورساتي',
 My_purchases: 'مشترياتي',
 Free: 'مجاناً',
 Published: 'نشر',
 draft: 'مسودة',
 waiting: 'انتظار',
 unpublish_request: 'طلبات نشر',
 Sales: 'مبيعات',
 new_sales: 'بيع جديد',
 new_postal_sales: 'New Postal Sales',
 New_message: 'رسالة جديدة',
 new_comment: 'تعليقات جديدة',
 account_summary: 'ملخص الحساب',
 Account_charge: 'شحن الرصيد',
 today_sales: 'مبيعات اليوم',
 monthly_sales: 'مبيعات الشهر',
 total_sale: 'اجمالي المبيعات',
 total_income: 'الدخل الكلي',
 Start_learning: 'ابدي اقره ودرس',
 Ready_to_payout: 'مستعد للدفع',
 start_teaching: 'ابدي قدم كورساتك اليوم',
 become_insructor: 'صير مدرس',
 total_purchase: 'المشتريات الكلية',
 current_sales_badge: 'باجات البيع الحالية',
 your_total_sales: 'اجمالي المبيعات',
 Balance: 'الرصيد',
 charge_account: 'شحن الرصيد',
 new_ticket: 'بطاقة جديدة',
 write_message: 'اكتب رسالتك',
 Attach: 'ارفاق ملف',
 close: 'اغلاق',
 reply_message: 'رد على الرسالة',
 new_messages: 'رسالة جديدة',
 Charge: 'شحن',
 purchased_items: 'شراء عنصر',
 sold_item: 'العنصر المباع',
 Automatic: 'تلقائي',
 manual: 'يدوي',
 Payoutable: 'قابل للدفع',
 replied: 'تم الرد',
 Reply: 'رد',
 Staff: 'الموظفين',
 empty_field: 'ميصير يبقى فارغ',
 Comments: 'تعليقات',
 Settings: 'الاعدادات',
 change_pass: 'تغيير كلمة المرور',
 Students: 'الطلاب',
 Instructor: 'الاساتذة',
 not_defined: 'غير مغرف',
 //Settings
 account_info: 'مغلومات الحساب',
 realname: 'الاسم الحقيقي الثلاثي',
 email: 'البريد الالكتروني',
 biography: 'معلومات شخصية',
 short_biography: 'مختصر عنك',
 province: 'المحافظة',
 city: 'المدينة',
 birthday: 'تاريخ الميلاد',
 age: 'العمر',
 name: 'الاسم',
 Save: 'حفظ',
 phone_number: 'رقم المحمول',
 personal_info: 'معلومات خاصة',
 bank_name: 'اسم المصرف ',
 account_number: 'رقم الحساب',
 creditcard: 'البطاقة الإتمانية',
 identity_scan: 'صورة الهوية',
 passport_id: 'رقم جواز السفر',
 images: 'صور',
 avatar: 'صورة شخصية',
 profile_cover: 'خلفية الصفحة الشخصية',
 new_password: 'كلمة مرور جديدة',
 retype_password: 'اعادة كلمة المرور',
 security: 'رمز الحماية',
 postal: 'رقم البريد',
 zip_code: 'Zip code',
 address: 'العنوان',
 financial_approved: 'تمت الموافقة على معلوماتك المالية ، لتغير هاي المعلومات الرجاء الإتصال بقسم الدعم',
 //Channel
 follow: 'متابعة  ',
 unfollow: 'الغاء المتابعة ',
 check:'التحقق',
 incorrect_code:'الكود غير صحيح',
 purchase_failed: 'فشل بالشراء ',
 no_credit:'رصيدك غير كافي',
 download:'تحميل',
 become_vendor:'صير مدرس',
 send_successfully:'تم الارسال بنجاح'
}

export {Lng}
